from turtletranslate.models.frontmatter import (
    FRONTMATTER_WORKER_SYSTEM,
    FRONTMATTER_WORKER_PROMPT,
)
from turtletranslate.models.summary import (
    SUMMARIZER_CRITIC_SYSTEM,
    SUMMARIZER_CRITIC_PROMPT,
    SUMMARIZER_WORKER_SYSTEM,
    SUMMARIZER_WORKER_PROMPT,
)
from turtletranslate.models.translation import (
    TRANSLATION_CRITIC_BLOCKQUOTE_SYSTEM,
    TRANSLATION_CRITIC_BLOCKQUOTE_PROMPT,
    TRANSLATION_CRITIC_ARTICLE_SYSTEM,
    TRANSLATION_CRITIC_ARTICLE_PROMPT,
    TRANSLATION_CRITIC_CODEFENCE_SYSTEM,
    TRANSLATION_CRITIC_CODEFENCE_PROMPT,
    TRANSLATION_CRITIC_WILDCARD_SYSTEM,
    TRANSLATION_CRITIC_WILDCARD_PROMPT,
    TRANSLATION_WORKER_BLOCKQUOTE_SYSTEM,
    TRANSLATION_WORKER_BLOCKQUOTE_PROMPT,
    TRANSLATION_WORKER_ARTICLE_SYSTEM,
    TRANSLATION_WORKER_ARTICLE_PROMPT,
    TRANSLATION_WORKER_CODEFENCE_SYSTEM,
    TRANSLATION_WORKER_CODEFENCE_PROMPT,
    TRANSLATION_WORKER_WILDCARD_SYSTEM,
    TRANSLATION_WORKER_WILDCARD_PROMPT,
    PREPEND_TRANSLATION_WORKER_SYSTEM,
    PREPEND_TRANSLATION_WORKER_PROMPT,
    PREPEND_TRANSLATION_CRITIC_SYSTEM,
    PREPEND_TRANSLATION_CRITIC_PROMPT,
)
