from turtletranslate.models.frontmatter import (
    FRONTMATTER_WORKER_SYSTEM,
    FRONTMATTER_WORKER_PROMPT,
)
from turtletranslate.models.summary import (
    SUMMARIZER_WORKER_SYSTEM,
    SUMMARIZER_CRITIC_SYSTEM,
    SUMMARIZER_CRITIC_PROMPT,
    SUMMARIZER_WORKER_PROMPT,
)
from turtletranslate.models.translation import (
    TRANSLATION_CRITIC_SYSTEM_BLOCKQUOTE,
    TRANSLATION_CRITIC_PROMPT_BLOCKQUOTE,
    TRANSLATION_CRITIC_SYSTEM_ARTICLE,
    TRANSLATION_CRITIC_PROMPT_ARTICLE,
    TRANSLATION_CRITIC_SYSTEM_CODEFENCE,
    TRANSLATION_CRITIC_PROMPT_CODEFENCE,
    TRANSLATION_CRITIC_SYSTEM_WILDCARD,
    TRANSLATION_CRITIC_PROMPT_WILDCARD,
    TRANSLATION_WORKER_SYSTEM_BLOCKQUOTE,
    TRANSLATION_WORKER_SYSTEM_ARTICLE,
    TRANSLATION_WORKER_SYSTEM_CODEFENCE,
    TRANSLATION_WORKER_SYSTEM_WILDCARD,
    TRANSLATION_WORKER_PROMPT_WILDCARD,
    TRANSLATION_WORKER_PROMPT_CODEFENCE,
    TRANSLATION_WORKER_PROMPT_ARTICLE,
    TRANSLATION_WORKER_PROMPT_BLOCKQUOTE,
)
