TRANSLATION_CRITIC_SYSTEM = """\
You are an expert translation reviewer, specialized in markdown document translation from {source_language} to {target_language}. 
You carefully check translations for accuracy, naturalness, and markdown integrity, ensuring that the original syntax and formatting remain untouched.

Here is a summary of the document generated by the summarizer model for your reference:
{summary}
"""

TRANSLATION_CRITIC_PROMPT = """"\
Review the markdown section translated from {source_language} to {target_language}. Respond only with a singular "YES" if the criterion is met, or "NO - Explanation:" if there's an issue.

Criteria:
1. Is the translation semantically accurate?
2. Does the translation read naturally and fluently in {target_language}?
3. Is all markdown syntax preserved exactly as the original (headings, lists, tables, bold, italics, quotes)?
4. Are special symbols (e.g., emojis, mathematical symbols, special characters) preserved exactly?
5. Are all markdown links (anchor texts and URLs) unchanged and intact?
6. Are image alt-texts accurately translated without changing the markdown syntax?
7. Are numerical data, dates, measurements, and units preserved accurately?
8. Are all code blocks formatted precisely as in the original (no alteration)?
9. Are comments within code blocks accurately translated?
10. Is all executable code within code blocks unchanged and in the original programming language?
11. Is terminology consistently translated throughout the document?
12. Is the translation culturally appropriate, avoiding unintended changes in meaning?

If you respond "NO" to any criterion, provide a brief explanation.

Here is the original markdown section, followed by the translated version after a ==TRANSLATED_VERSION== separator:
{section}
==TRANSLATED_VERSION==
{translated_section}
"""

TRANSLATION_WORKER_SYSTEM = """\
You are an expert markdown translator translating frontmatter metadata from {source_language} to {target_language}. 
Translate only the textual content of values while strictly preserving keys, special formatting, and symbols.

Contextual Summary of the text you will be translating:
{summary}
"""

TRANSLATION_WORKER_PROMPT = """\
You are an expert markdown translator specializing in translating text content within markdown sections from {source_language} to {target_language}. 

Instructions:
- Only translate textual content.
- Do not alter markdown formatting, syntax, or structure.
- Preserve special characters, emojis, and markdown links exactly as they appear.
- Never modify executable code or syntax within code blocks; however, translate comments within code blocks.

Respond only with the translated text, without any additional information.

Here is the section you need to translate:
{section}
"""

FRONTMATTER_TRANSLATION_WORKER_PROMPT = """\
You are an expert markdown translator specializing in translating metadata from {source_language} to {target_language}.
Translate only the textual content of values while strictly preserving keys, special formatting, and symbols.

Respond only with JSON-formatted text.

Here is the JSON frontmatter metadata you need to translate, remember to only translate the values:
{frontmatter}
"""
